Solution/find the neighbour
tomorrowdevs-projects/challenges pull request #5
Opened 2021-08-24 13:19 UTC by ederalab

2021-08-24 13:20 UTC, ederalab commented
Reviewers:
@micheleriva 
@Gsantomaggio

2021-08-30 08:26 UTC, micheleriva requested changes
The solution is awesome, but please remove the other challenge file!

2021-08-30 08:26 UTC, micheleriva commented on challenges/easy/clean-up-after-your-dog/solutions/valentinadagata/main.py
> +def cleanUp(garden, bags, cap):
This file refers to another challenge, please delete it before merging the PR

2021-08-30 08:26 UTC, micheleriva commented on challenges/intermediate/find-the-neighbour/solutions/valentinadagata/main.py
> +    matrix = [newcube[x:x + rows_cols] for x in range(0, len(newcube), rows_cols)]
nice usage of list comprehension, I like it

2021-09-04 11:19 UTC, micheleriva commented
@ederalab it looks like you have a conflict on the `challenges/easy/clean-up-after-your-dog/solutions/valentinadagata/main.py` file. Could you please resolve this so that I can merge your PR? Thanks!

2021-09-06 18:02 UTC, ederalab commented
I updated the file and I hope the new one has no conflicts. I also deleted  the "clean-up-after-your-dog" files from the local branch

2021-09-10 10:07 UTC, closed without merging